; 定义模型（Model）

; 定义了请求的属性，包括 sub（subject，主体）、obj（object，对象）、act（action，动作）
[request_definition]
r = sub, obj, act

; 定义了策略的属性，包括 sub、obj、act等，与请求属性相同
[policy_definition]
p = sub, obj, act

; 定义了角色的属性，这里使用 _ 表示通配符，表示任意角色
[role_definition]
g = _, _

; 定义了策略的生效规则，使用了 Casbin 提供的内置函数和操作符
[policy_effect]
e = some(where (p.eft == allow))

; 定义了匹配规则，这里使用了 g 函数来匹配角色
[matchers]
m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act